name: youdao # you probably want to 'snapcraft register <name>'
version: '0.1' # just for humans, typically '1.2+git' or '1.3.2'
summary: youdao
description: |
  This is youdao

grade: devel # must be 'stable' to release into candidate/stable channels
confinement: classic # use 'strict' once you have the right plugs and slots

apps:
  youdao:
    command: bin/desktop-launch  $SNAP/usr/share/youdao-dict/main.py

parts:
  app:
    plugin: dump
    source: ./youdao-dict_1.1.0-0-ubuntu_amd64.deb

  py:
    plugin: python3
    source: .
    stage-packages:
      - pyqt5-dev
      - python3-pyqt5
      - python3-requests
      - python3-xlib
      - python3-lxml
      - python3-xdg
      - python3-pyqt5.qtmultimedia
      - python3-pyqt5.qtquick
      - python3-pyqt5.qtwebkit
      - gir1.2-appindicator3-0.1
      - python3-dbus
      - qtdeclarative5-controls-plugin
      - libqt5multimedia5-plugins
      - gstreamer1.0-plugins-ugly
      - tesseract-ocr
      - tesseract-ocr-eng
      - tesseract-ocr-chi-sim
      - tesseract-ocr-chi-tra
      - python3-pil
      - ttf-wqy-microhei
    after: [desktop-gtk3]

